version: '3'
services:
  user:
    build: 
      dockerfile: ./Dockerfile
      args:
        project: ./user
    environment:
      PORT: 8081
      APP_NAME: user
    restart: on-failure
    volumes:
      - type: bind
        source: ./user/cmd
        target: /usr/src/user
        read_only: true
    network_mode: host

volumes:
  user_vol:


networks:
  default:
    name: host
    external: true
