version: '3'
services:
  example:
    build: ./golang
    dockerfile: ./Dockerfile
    args:
      project: ./cmd/example
  environment:
    - PORT=3001
    - APP_NAME=example
  ports:
    - 8001:3001
  restart: on-failure
  volumes:
    - example_vol:/usr/src/example/
  networks:
    - example_net

volumes:
  example_vol:

networks:
  monorepo_net:
    driver: bridge